### ISSUE TITLE
laravel下耦合性问题

### ISSUE THREAD

**Issue by yu1ec** [hyperf/jet#15]
我在laravel8下进行rpc调试的时候，安装了hyperf/jet插件，然后就出现了以下报错
![image](https://user-images.githubusercontent.com/2928867/97945367-4eedcb80-1dc2-11eb-844a-c69c7b7503f3.png)

应该是hyperf/jet中的依赖库hyperf/utils里有一个类Collection和laravel中的Collection冲突了，但是我不清楚咋解决，所以提个issue。

**Comment by limingxinleo** [comment]
这个比较坑。。。

你入口文件里，把laravel得helper主动require一下

**Comment by yu1ec** [comment]
只有这个办法吗？我本来是想封装成我们公司内部扩展的，这样的话，估计还不行呢

**Comment by limingxinleo** [comment]
封装成内部扩展，和入口函数搞一下，没差的。

**Comment by limingxinleo** [comment]
你可以 fork 一份 hyperf/utils 然后去掉 file 加载那里，然后在你自己的组件里引入这个组件。

然后 replace 掉 hyperf/utils 就行了。

**Comment by yu1ec** [comment]
嗯，我已经在这么干了。哈哈，基本上就是拷贝了一份，去除了相关的依赖。

**Comment by yu1ec** [comment]
@limingxinleo 大佬，这个解耦要不空了也考虑下 。我一开始也天真的以为改一个包的内容就行了，但是后来发现，他们互相依赖，然后为了jet所有的功能，我一下子改了4个包。
![image](https://user-images.githubusercontent.com/2928867/98362273-e9226d80-2067-11eb-9a14-71d0e7080718.png)

**Comment by limingxinleo** [comment]
。。。你想的太麻烦了

只需要改hyperf/utils就行啊

**Comment by yu1ec** [comment]
但是，你这几个扩展里出了hyperf/consul我是需要改一点功能外，rpc和jet都引入了hyperf/utils，而且psr4那边也注册了，laravel只要一加载这两个当中任意一个，就会报错。
