### ISSUE TITLE
StreamSocketTransporter接收数据时有纪律陷入死循环

### ISSUE THREAD

**Issue by caiking** [hyperf/jet#18]
以上代码在对端服务重启时，如果有未完成的请求，stream_select返回的仍然是1，会陷入死循环的空跑中，导致cpu飙升至100%

while (stream_select($read, $write, $except, 0, $timeout)) {
                foreach ($read as $r) {
                    $buf .= fread($r, 8192);
                }
}

**Comment by huangzhhui** [comment]
@caiking 这个 issue close 掉了是因为？

**Comment by limingxinleo** [comment]
这个问题应该已经处理过了
