### ISSUE TITLE
Class 'Hyperf\Consul\Health' not found

### ISSUE THREAD

**Issue by Observer5** [hyperf/jet#22]
hyperf/jet 4.0.0
laravel使用
报错信息：
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Hyperf\Consul\Health' not found

/vendor/hyperf/jet/src/NodeSelector/NodeSelector.php:61

**Comment by limingxinleo** [comment]
![image](https://user-images.githubusercontent.com/16648551/128863632-cda3b24c-0fc8-4669-966b-095d2b7799e5.png)

如果你要用 consul 就安装 hyperf/concul 

不然就不要用 consul

**Comment by Observer5** [comment]
- hyperf/guzzle v2.2.0 requires hyperf/utils ~2.2.0 -> found hyperf/utils[v2.2.0] but the package is fixed to v2.1.14 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - hyperf/consul v2.2.0 requires hyperf/guzzle ~2.2.0 -> satisfiable by hyperf/guzzle[v2.2.0].
    - Root composer.json requires hyperf/consul ^2.2 -> satisfiable by hyperf/consul[v2.2.0].

还没支持到2.2
