### ISSUE TITLE
想知道啥时候能在支持上下文传递.....

### ISSUE THREAD

**Issue by SSN-YeChen** [hyperf/jet#25]
因为目前包不支持上下文传递....目前只能通过参数传递操作用户的信息....

**Comment by huangzhhui** [comment]
什么叫做不支持上下文传递？

**Comment by SSN-YeChen** [comment]
希望在 DataFormatter -> formatRequest  增加 context
![image](https://user-images.githubusercontent.com/28284838/145767740-cdbe1224-1b91-49ae-b8e0-8d14bed0e567.png)

这样在在hpyerf,通过Hyperf\Rpc\Context 就能获取到上下文了...

PS：因为是在laravel下使用Jet，没有安装swoole扩展情况下，无发通过Hyperf\Utils\Context 来传递...
