### ISSUE TITLE
在其他php框架使用时，会发生错误Collection 在其他框架里也有存在，所以不能直接用Collection去调用，会报错，比如thinkphp中

### ISSUE THREAD

**Issue by marktao** [hyperf/jet#26]
![image](https://user-images.githubusercontent.com/11715499/229485473-31de5632-22c6-4526-bbe9-dc4372ca8ec0.png)

需要做上述调整才可以正常使用

**Comment by limingxinleo** [comment]
使用最新版本，已经处理了
