### ISSUE TITLE
jsonRpc调用数据包太大数据被截断

### ISSUE THREAD

**Issue by Uestczhouxin** [hyperf/jet#5]
StreamSocketTransporter.php文件中recv方法，数据包长度超过8192时会被截断

**Comment by Uestczhouxin** [comment]
@huangzhhui 大佬能帮忙看看么

**Comment by huangzhhui** [comment]
请先提供重现代码，光描述不会有助于问题的解决

**Comment by kylinlxl** [comment]
Hyperf\Jet\Transporter\StreamSocketTransporter.php
`    public function recv()
    {
        return fread($this->client, 65535);
    }`
recv()方法没有考虑数据量大的情况，没有循环取数据接收所有数据为止，这个方法里面，fread($this->client, 65535), 虽然写了65535， 但是fread一次只能接收8192个字节

**Comment by limingxinleo** [comment]
嗯，这周处理一下。。

**Comment by kylinlxl** [comment]
@limingxinleo 这个问题解决了吗？

**Comment by limingxinleo** [comment]
> @limingxinleo 这个问题解决了吗？

还没有，最近都在忙Phpcon的事

**Comment by Linij** [comment]
兄弟，我已经修复了这个问题，在 pull request 里面了
